### ISSUE TITLE
resultCode":"1007

### ISSUE THREAD

**Issue by Ankit7791** [aniket-yadav/paytm_demo#2]
{"head":{"requestId":null,"responseTimestamp":"1658838951200","version":"v1"},"body":{"extraParamsMap":null,"resultInfo":{"resultStatus":"F","resultCode":"1007","resultMsg":"Missing
mandatory element"}}}

**Comment by aniket-yadav** [comment]
@Ankit7791 Please share in which API you are getting this

**Comment by Ankit7791** [comment]
Generate Token

**Comment by Ankit7791** [comment]
`<?php

require_once("PaytmChecksum.php");
include 'paytm_credentials.php';


$amount = $_POST["amount"];


$paytmParams = array();
$orderId = "ORDERID_".mt_rand(); 
$paytmParams["body"] = array(
 "requestType"  => "Payment",
 "mid"  =>  $merchantId, 
 "websiteName"  => "WEBSTAGING",
 "industryType" => "Retail",
 "orderId"  => $orderId,
 "callbackurl"  => "https://securegw-stage.paytm.in/theia/paytmCallback?ORDER_ID=".$orderId,
 "txnAmount"  => array("value" => $amount,"currency" => "INR",),
 "userInfo" => array("custId" => "CUST_".mt_rand(),"mobile"=> '7777777777'),
 ); 


$checksum = PaytmChecksum::generateSignature(json_encode($paytmParams["body"], JSON_UNESCAPED_SLASHES), $merchantKey);

$paytmParams["head"] = array(
 "signature" => $checksum 
);

$post_data = json_encode($paytmParams, JSON_UNESCAPED_SLASHES);

$url = "https://securegw-stage.paytm.in/theia/api/v1/initiateTransaction?mid=$merchantId&orderId=$orderId";

$ch = curl_init($url);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $post_data);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, array("Content-Type: application/json"));
$res = curl_exec($ch);
$res_json = json_decode($res,true);

print_r($res);

if($res_json["body"]["resultInfo"]["resultCode"] == "0000"){ 
 

    $response = array();
    $response["mid"] = $merchantId;
    $response["txToken"]= $res_json["body"]["txnToken"];
    $response["orderId"] = $orderId;
echo json_encode($response);

}else{
    
 http_response_code($res_json["body"]["resultInfo"]["resultCode"]);
     echo $res_json["body"]["resultInfo"]["resultMsg"];
}
?>`

**Comment by Ankit7791** [comment]
Found this code working though 

`<?php
/*
* import checksum generation utility
* You can get this utility from https://developer.paytm.com/docs/checksum/
*/
require("PaytmChecksum.php");

$mid=$_POST["mid"];
$orderId=$_POST["ORDERID"];
$amount=$_POST["amount"];
$key=$_POST["mkey"];
$custId=$_POST["custId"];
$url=$_POST["url"];
$websiteName=$_POST["web"];


// $mid="zlsjBq52825503339453";


$paytmParams = array();

$paytmParams["body"] = array(
"requestType" => "Payment",
"mid" =>$mid,
"websiteName" =>$websiteName,
"orderId"  =>$orderId,
"callbackurl" =>"https://merchant.com/callback",
"txnAmount" => array(
"value"=>$amount,
"currency" => "INR"
 ),
"userInfo" => array(
"custId" =>$custId
 )
);


$checksum = PaytmChecksum::generateSignature(json_encode($paytmParams["body"],JSON_UNESCAPED_SLASHES),$key);
$paytmParams["head"] = array(
"signature" => $checksum 
);

$post_data =json_encode($paytmParams,JSON_UNESCAPED_SLASHES);

/* for Staging */



 $url = "$url/theia/api/v1/initiateTransaction?mid=$mid&orderId=$orderId";

$ch =curl_init($url);

curl_setopt($ch,CURLOPT_POST,1);
curl_setopt($ch,CURLOPT_POSTFIELDS,$post_data);
curl_setopt($ch,CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, array("Content-Type: application/json"));
$resp=curl_exec($ch);
print($resp);



?>`

**Comment by aniket-yadav** [comment]
@Ankit7791   this is working but I am getting a session expired error, are you getting this too?

**Comment by Ankit7791** [comment]
No I am not getting it , second one that i have pasted is working fine , first one is your code that is throwing error

**Comment by aniket-yadav** [comment]
are you able to make a transaction?

**Comment by aniket-yadav** [comment]
@Ankit7791  I am getting this error 
PlatformException(0, Your Session has expired., null, null)

**Comment by Ankit7791** [comment]
with your code I am not able to make it

**Comment by aniket-yadav** [comment]
I have updated my code for token generation

**Comment by Ankit7791** [comment]
ok i will check than
